version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_data:/app/media
      - backup_data:/app/respaldo/backup
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      MYSQL_DATABASE: "EcoGest"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "example"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "EcoGest"
      MYSQL_ROOT_PASSWORD: "example"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  media_data:
  backup_data:
